#!/bin/bash

cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/f493ae2c-f65b-4e35-9049-dcfb2aa2d2c9/call-myTask/execution
tmpDir=$(mkdir -p "/Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/f493ae2c-f65b-4e35-9049-dcfb2aa2d2c9/call-myTask/tmp.eb8ce622" && echo "/Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/f493ae2c-f65b-4e35-9049-dcfb2aa2d2c9/call-myTask/tmp.eb8ce622")

export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/f493ae2c-f65b-4e35-9049-dcfb2aa2d2c9/call-myTask/execution

)
outf493ae2c="${tmpDir}/out.$$" errf493ae2c="${tmpDir}/err.$$"
mkfifo "$outf493ae2c" "$errf493ae2c"
trap 'rm "$outf493ae2c" "$errf493ae2c"' EXIT
tee '/Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/f493ae2c-f65b-4e35-9049-dcfb2aa2d2c9/call-myTask/execution/stdout' < "$outf493ae2c" &
tee '/Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/f493ae2c-f65b-4e35-9049-dcfb2aa2d2c9/call-myTask/execution/stderr' < "$errf493ae2c" >&2 &
(
cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/f493ae2c-f65b-4e35-9049-dcfb2aa2d2c9/call-myTask/execution


set -exo pipefail
mkdir bundle
tar -xzf /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/f493ae2c-f65b-4e35-9049-dcfb2aa2d2c9/call-myTask/inputs/-223602523/bundle.tar.gz -C bundle
mv bundle/*/* bundle
PWD=/Users/mkumar1/Desktop/apps/Exomiser
python3 /Users/mkumar1/wdl/cromwell/script.py -t $PWD/bundle/exomiser_genome_template_b38.yml -o bundle.tar.gz.out_file
)  > "$outf493ae2c" 2> "$errf493ae2c"
echo $? > /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/f493ae2c-f65b-4e35-9049-dcfb2aa2d2c9/call-myTask/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/f493ae2c-f65b-4e35-9049-dcfb2aa2d2c9/call-myTask/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/f493ae2c-f65b-4e35-9049-dcfb2aa2d2c9/call-myTask/execution
sync


)
mv /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/f493ae2c-f65b-4e35-9049-dcfb2aa2d2c9/call-myTask/execution/rc.tmp /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/f493ae2c-f65b-4e35-9049-dcfb2aa2d2c9/call-myTask/execution/rc
