#!/bin/bash

cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/2d91da24-3073-496b-9915-9ff56140ab60/call-myTask/execution
tmpDir=$(mkdir -p "/Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/2d91da24-3073-496b-9915-9ff56140ab60/call-myTask/tmp.ea1d1a0f" && echo "/Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/2d91da24-3073-496b-9915-9ff56140ab60/call-myTask/tmp.ea1d1a0f")

export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/2d91da24-3073-496b-9915-9ff56140ab60/call-myTask/execution

)
out2d91da24="${tmpDir}/out.$$" err2d91da24="${tmpDir}/err.$$"
mkfifo "$out2d91da24" "$err2d91da24"
trap 'rm "$out2d91da24" "$err2d91da24"' EXIT
tee '/Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/2d91da24-3073-496b-9915-9ff56140ab60/call-myTask/execution/stdout' < "$out2d91da24" &
tee '/Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/2d91da24-3073-496b-9915-9ff56140ab60/call-myTask/execution/stderr' < "$err2d91da24" >&2 &
(
cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/2d91da24-3073-496b-9915-9ff56140ab60/call-myTask/execution


set -exo pipefail
mkdir bundle
echo /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/2d91da24-3073-496b-9915-9ff56140ab60/call-myTask/inputs/-223602523/bundle.tar.gz
tar -xzf /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/2d91da24-3073-496b-9915-9ff56140ab60/call-myTask/inputs/-223602523/bundle.tar.gz -C bundle
mv bundle/*/* bundle
PWD=/Users/mkumar1/wdl/tar_example
python3 /Users/mkumar1/wdl/tar_example/script.py -t $PWD/bundle/exomiser_genome_template_b38.yml -o bundle.tar.gz.out_file
)  > "$out2d91da24" 2> "$err2d91da24"
echo $? > /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/2d91da24-3073-496b-9915-9ff56140ab60/call-myTask/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/2d91da24-3073-496b-9915-9ff56140ab60/call-myTask/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/2d91da24-3073-496b-9915-9ff56140ab60/call-myTask/execution
sync


)
mv /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/2d91da24-3073-496b-9915-9ff56140ab60/call-myTask/execution/rc.tmp /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/2d91da24-3073-496b-9915-9ff56140ab60/call-myTask/execution/rc
