#!/bin/bash

cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/27aa7a92-7246-4e2e-a58d-8fac10fe4045/call-myTask/execution
tmpDir=$(mkdir -p "/Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/27aa7a92-7246-4e2e-a58d-8fac10fe4045/call-myTask/tmp.29e07903" && echo "/Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/27aa7a92-7246-4e2e-a58d-8fac10fe4045/call-myTask/tmp.29e07903")

export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/27aa7a92-7246-4e2e-a58d-8fac10fe4045/call-myTask/execution

)
out27aa7a92="${tmpDir}/out.$$" err27aa7a92="${tmpDir}/err.$$"
mkfifo "$out27aa7a92" "$err27aa7a92"
trap 'rm "$out27aa7a92" "$err27aa7a92"' EXIT
tee '/Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/27aa7a92-7246-4e2e-a58d-8fac10fe4045/call-myTask/execution/stdout' < "$out27aa7a92" &
tee '/Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/27aa7a92-7246-4e2e-a58d-8fac10fe4045/call-myTask/execution/stderr' < "$err27aa7a92" >&2 &
(
cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/27aa7a92-7246-4e2e-a58d-8fac10fe4045/call-myTask/execution


set -exo pipefail
mkdir bundle
tar -xzf /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/27aa7a92-7246-4e2e-a58d-8fac10fe4045/call-myTask/inputs/-223602523/bundle.tar.gz -C bundle
mv bundle/*/* bundle
PWD=/Users/mkumar1/Desktop/apps/Exomiser
python3 /Users/mkumar1/wdl/cromwell/script.py -t $PWD/bundle/exomiser_genome_template_b38.yml -o bundle.tar.gz.out_file
)  > "$out27aa7a92" 2> "$err27aa7a92"
echo $? > /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/27aa7a92-7246-4e2e-a58d-8fac10fe4045/call-myTask/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/27aa7a92-7246-4e2e-a58d-8fac10fe4045/call-myTask/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/27aa7a92-7246-4e2e-a58d-8fac10fe4045/call-myTask/execution
sync


)
mv /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/27aa7a92-7246-4e2e-a58d-8fac10fe4045/call-myTask/execution/rc.tmp /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/27aa7a92-7246-4e2e-a58d-8fac10fe4045/call-myTask/execution/rc
