#!/bin/bash

cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/3f42679e-4208-4dda-99ad-9112e8c22663/call-myTask/execution
tmpDir=$(mkdir -p "/Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/3f42679e-4208-4dda-99ad-9112e8c22663/call-myTask/tmp.04728e0c" && echo "/Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/3f42679e-4208-4dda-99ad-9112e8c22663/call-myTask/tmp.04728e0c")

export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/3f42679e-4208-4dda-99ad-9112e8c22663/call-myTask/execution

)
out3f42679e="${tmpDir}/out.$$" err3f42679e="${tmpDir}/err.$$"
mkfifo "$out3f42679e" "$err3f42679e"
trap 'rm "$out3f42679e" "$err3f42679e"' EXIT
tee '/Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/3f42679e-4208-4dda-99ad-9112e8c22663/call-myTask/execution/stdout' < "$out3f42679e" &
tee '/Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/3f42679e-4208-4dda-99ad-9112e8c22663/call-myTask/execution/stderr' < "$err3f42679e" >&2 &
(
cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/3f42679e-4208-4dda-99ad-9112e8c22663/call-myTask/execution


set -exo pipefail
mkdir bundle
tar -xzf /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/3f42679e-4208-4dda-99ad-9112e8c22663/call-myTask/inputs/-223602523/bundle.tar.gz -C bundle
mv bundle/*/* bundle
PWD=/Users/mkumar1/wdl/tar_example
python3 /Users/mkumar1/wdl/tar_example/script.py -t $PWD/bundle/exomiser_genome_template_b38.yml -o bundle.tar.gz.out_file
)  > "$out3f42679e" 2> "$err3f42679e"
echo $? > /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/3f42679e-4208-4dda-99ad-9112e8c22663/call-myTask/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/3f42679e-4208-4dda-99ad-9112e8c22663/call-myTask/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/3f42679e-4208-4dda-99ad-9112e8c22663/call-myTask/execution
sync


)
mv /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/3f42679e-4208-4dda-99ad-9112e8c22663/call-myTask/execution/rc.tmp /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/3f42679e-4208-4dda-99ad-9112e8c22663/call-myTask/execution/rc
