#!/bin/bash

cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/73064673-a3e2-4d05-90d9-505d8ebc376b/call-myTask/execution
tmpDir=$(mkdir -p "/Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/73064673-a3e2-4d05-90d9-505d8ebc376b/call-myTask/tmp.b9c7fce4" && echo "/Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/73064673-a3e2-4d05-90d9-505d8ebc376b/call-myTask/tmp.b9c7fce4")

export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/73064673-a3e2-4d05-90d9-505d8ebc376b/call-myTask/execution

)
out73064673="${tmpDir}/out.$$" err73064673="${tmpDir}/err.$$"
mkfifo "$out73064673" "$err73064673"
trap 'rm "$out73064673" "$err73064673"' EXIT
tee '/Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/73064673-a3e2-4d05-90d9-505d8ebc376b/call-myTask/execution/stdout' < "$out73064673" &
tee '/Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/73064673-a3e2-4d05-90d9-505d8ebc376b/call-myTask/execution/stderr' < "$err73064673" >&2 &
(
cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/73064673-a3e2-4d05-90d9-505d8ebc376b/call-myTask/execution


set -exo pipefail
mkdir bundle
echo /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/73064673-a3e2-4d05-90d9-505d8ebc376b/call-myTask/inputs/-223602523/bundle.tar.gz
tar -xzf /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/73064673-a3e2-4d05-90d9-505d8ebc376b/call-myTask/inputs/-223602523/bundle.tar.gz -C bundle
path=$(realpath bundle)
echo $path 
mv bundle/*/* bundle
python3 /Users/mkumar1/wdl/tar_example/script.py -t $path/exomiser_genome_template_b38.yml -o bundle.tar.gz.out_file
)  > "$out73064673" 2> "$err73064673"
echo $? > /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/73064673-a3e2-4d05-90d9-505d8ebc376b/call-myTask/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/73064673-a3e2-4d05-90d9-505d8ebc376b/call-myTask/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/73064673-a3e2-4d05-90d9-505d8ebc376b/call-myTask/execution
sync


)
mv /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/73064673-a3e2-4d05-90d9-505d8ebc376b/call-myTask/execution/rc.tmp /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/73064673-a3e2-4d05-90d9-505d8ebc376b/call-myTask/execution/rc
