#!/bin/bash

cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/d8efdf28-4dc0-473b-b7dc-75ab1e477015/call-myTask/execution
tmpDir=$(mkdir -p "/Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/d8efdf28-4dc0-473b-b7dc-75ab1e477015/call-myTask/tmp.1137cc73" && echo "/Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/d8efdf28-4dc0-473b-b7dc-75ab1e477015/call-myTask/tmp.1137cc73")

export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/d8efdf28-4dc0-473b-b7dc-75ab1e477015/call-myTask/execution

)
outd8efdf28="${tmpDir}/out.$$" errd8efdf28="${tmpDir}/err.$$"
mkfifo "$outd8efdf28" "$errd8efdf28"
trap 'rm "$outd8efdf28" "$errd8efdf28"' EXIT
tee '/Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/d8efdf28-4dc0-473b-b7dc-75ab1e477015/call-myTask/execution/stdout' < "$outd8efdf28" &
tee '/Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/d8efdf28-4dc0-473b-b7dc-75ab1e477015/call-myTask/execution/stderr' < "$errd8efdf28" >&2 &
(
cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/d8efdf28-4dc0-473b-b7dc-75ab1e477015/call-myTask/execution


set -exo pipefail
mkdir bundle
echo /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/d8efdf28-4dc0-473b-b7dc-75ab1e477015/call-myTask/inputs/-223602523/bundle.tar.gz
tar -xzf /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/d8efdf28-4dc0-473b-b7dc-75ab1e477015/call-myTask/inputs/-223602523/bundle.tar.gz -C bundle
bundlepath=$(realpath bundle)       
mv bundle/*/* bundle
PWD=/Users/mkumar1/wdl/tar_example
python3 /Users/mkumar1/wdl/tar_example/script.py -t $PWD/bundle/exomiser_genome_template_b38.yml -o bundle.tar.gz.out_file
)  > "$outd8efdf28" 2> "$errd8efdf28"
echo $? > /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/d8efdf28-4dc0-473b-b7dc-75ab1e477015/call-myTask/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/d8efdf28-4dc0-473b-b7dc-75ab1e477015/call-myTask/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/d8efdf28-4dc0-473b-b7dc-75ab1e477015/call-myTask/execution
sync


)
mv /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/d8efdf28-4dc0-473b-b7dc-75ab1e477015/call-myTask/execution/rc.tmp /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/d8efdf28-4dc0-473b-b7dc-75ab1e477015/call-myTask/execution/rc
