#!/bin/bash

cd /cromwell-executions/myWorkflow/60bd4dad-326f-4023-b21b-eb8bc9cce99d/call-myTask/execution
tmpDir=$(mkdir -p "/cromwell-executions/myWorkflow/60bd4dad-326f-4023-b21b-eb8bc9cce99d/call-myTask/tmp.dcbec076" && echo "/cromwell-executions/myWorkflow/60bd4dad-326f-4023-b21b-eb8bc9cce99d/call-myTask/tmp.dcbec076")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/myWorkflow/60bd4dad-326f-4023-b21b-eb8bc9cce99d/call-myTask/execution

)
out60bd4dad="${tmpDir}/out.$$" err60bd4dad="${tmpDir}/err.$$"
mkfifo "$out60bd4dad" "$err60bd4dad"
trap 'rm "$out60bd4dad" "$err60bd4dad"' EXIT
tee '/cromwell-executions/myWorkflow/60bd4dad-326f-4023-b21b-eb8bc9cce99d/call-myTask/execution/stdout' < "$out60bd4dad" &
tee '/cromwell-executions/myWorkflow/60bd4dad-326f-4023-b21b-eb8bc9cce99d/call-myTask/execution/stderr' < "$err60bd4dad" >&2 &
(
cd /cromwell-executions/myWorkflow/60bd4dad-326f-4023-b21b-eb8bc9cce99d/call-myTask/execution


        set -exo pipefail
        mkdir bundle
        echo /cromwell-executions/myWorkflow/60bd4dad-326f-4023-b21b-eb8bc9cce99d/call-myTask/inputs/1960677953/exomiser_input.tar.gz
        tar -xzf /cromwell-executions/myWorkflow/60bd4dad-326f-4023-b21b-eb8bc9cce99d/call-myTask/inputs/1960677953/exomiser_input.tar.gz -C bundle
        path=$(realpath bundle)
        echo $path 
        mv bundle/*/* bundle
`
       
        mkdir -p $path/output
        #mkdir -p 'b38.application.properties_result'/output

        while IFS= read -r line
        do
          if [[ "$line" == *"vcf:"* ]]; then
             vcf="$(cut -d':' -f1 <<<"$line")"
             vcf_fname="$(cut -d':' -f2 <<<"$line")"
             vcf_name=`echo $vcf_fname | sed 's/ *$//g'`
             echo "$vcf: $path/"$vcf_name >> 'b38.application.properties.yaml.tmp'
          elif [[ "$line" == *"ped:"* ]]; then
             ped="$(cut -d':' -f1 <<<"$line")"
             ped_name="$(cut -d':' -f2 <<<"$line")"
             ped_fname=`echo $ped_name | sed 's/ *$//g'`
             echo "$ped: $path/"$ped_fname >> 'b38.application.properties.yaml.tmp'
          elif [[ "$line" == *"outputPrefix:"* ]]; then
             oprefix="$(cut -d':' -f1 <<<"$line")"
             oprefix_name_name="$(cut -d':' -f2 <<<"$line")"
             prefix_name=`echo $oprefix_name | sed 's/ *$//g'`
             echo "$oprefix: $path/"$prefix_fname"/output/result" >> 'b38.application.properties.yaml.tmp'
             #echo "$oprefix: b38.application.properties_result/output/result" >> 'b38.application.properties.yaml.tmp'
          else
             echo "$line" >> 'b38.application.properties.yaml.tmp'
          fi
        done < "/cromwell-executions/myWorkflow/60bd4dad-326f-4023-b21b-eb8bc9cce99d/call-myTask/inputs/1960677953/exomiser.yaml"
        mv 'b38.application.properties.yaml.tmp' '/cromwell-executions/myWorkflow/60bd4dad-326f-4023-b21b-eb8bc9cce99d/call-myTask/inputs/1960677953/exomiser.yaml'

        while IFS= read -r line
        do
          if [[ "$line" == "exomiser.data-directory"* ]]; then
             A="$(cut -d'=' -f1 <<<"$line")"
             echo "$A=$path" >> 'b38.application.properties.tmp'
          else
             echo "$line" >> 'b38.application.properties.tmp'
          fi
        done < "/cromwell-executions/myWorkflow/60bd4dad-326f-4023-b21b-eb8bc9cce99d/call-myTask/inputs/1960677953/b38.application.properties"
               
        mv 'b38.application.properties.tmp' '/cromwell-executions/myWorkflow/60bd4dad-326f-4023-b21b-eb8bc9cce99d/call-myTask/inputs/1960677953/b38.application.properties'

        java -Xms2g -Xmx8g -jar /software/reboot-utils/exomiser-cli-12.1.0/exomiser-cli-12.1.0.jar --analysis /cromwell-executions/myWorkflow/60bd4dad-326f-4023-b21b-eb8bc9cce99d/call-myTask/inputs/1960677953/exomiser.yaml --spring.config.location=/cromwell-executions/myWorkflow/60bd4dad-326f-4023-b21b-eb8bc9cce99d/call-myTask/inputs/1960677953/b38.application.properties
        tar czvf $path/output.tar.gz $path/output 
        mkdir -p 'b38.application.properties_result' 
        cp $path/output.tar.gz 'b38.application.properties_result/output.tar.gz'
)  > "$out60bd4dad" 2> "$err60bd4dad"
echo $? > /cromwell-executions/myWorkflow/60bd4dad-326f-4023-b21b-eb8bc9cce99d/call-myTask/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/myWorkflow/60bd4dad-326f-4023-b21b-eb8bc9cce99d/call-myTask/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/myWorkflow/60bd4dad-326f-4023-b21b-eb8bc9cce99d/call-myTask/execution
sync


)
mv /cromwell-executions/myWorkflow/60bd4dad-326f-4023-b21b-eb8bc9cce99d/call-myTask/execution/rc.tmp /cromwell-executions/myWorkflow/60bd4dad-326f-4023-b21b-eb8bc9cce99d/call-myTask/execution/rc
