#!/bin/bash

cd /cromwell-executions/myWorkflow/3d472760-433f-4177-8445-2b0bc04642cb/call-myTask/execution
tmpDir=$(mkdir -p "/cromwell-executions/myWorkflow/3d472760-433f-4177-8445-2b0bc04642cb/call-myTask/tmp.e37ea83c" && echo "/cromwell-executions/myWorkflow/3d472760-433f-4177-8445-2b0bc04642cb/call-myTask/tmp.e37ea83c")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/myWorkflow/3d472760-433f-4177-8445-2b0bc04642cb/call-myTask/execution

)
out3d472760="${tmpDir}/out.$$" err3d472760="${tmpDir}/err.$$"
mkfifo "$out3d472760" "$err3d472760"
trap 'rm "$out3d472760" "$err3d472760"' EXIT
tee '/cromwell-executions/myWorkflow/3d472760-433f-4177-8445-2b0bc04642cb/call-myTask/execution/stdout' < "$out3d472760" &
tee '/cromwell-executions/myWorkflow/3d472760-433f-4177-8445-2b0bc04642cb/call-myTask/execution/stderr' < "$err3d472760" >&2 &
(
cd /cromwell-executions/myWorkflow/3d472760-433f-4177-8445-2b0bc04642cb/call-myTask/execution


set -exo pipefail
mkdir bundle
echo /cromwell-executions/myWorkflow/3d472760-433f-4177-8445-2b0bc04642cb/call-myTask/inputs/-223602523/bundle.tar.gz
tar -xzf /cromwell-executions/myWorkflow/3d472760-433f-4177-8445-2b0bc04642cb/call-myTask/inputs/-223602523/bundle.tar.gz -C bundle
path=$(realpath bundle)
echo $path 
mv bundle/*/* bundle
python3 /script.py -t $path/exomiser_genome_template_b38.yml -o bundle.tar.gz.out_file
)  > "$out3d472760" 2> "$err3d472760"
echo $? > /cromwell-executions/myWorkflow/3d472760-433f-4177-8445-2b0bc04642cb/call-myTask/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/myWorkflow/3d472760-433f-4177-8445-2b0bc04642cb/call-myTask/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/myWorkflow/3d472760-433f-4177-8445-2b0bc04642cb/call-myTask/execution
sync


)
mv /cromwell-executions/myWorkflow/3d472760-433f-4177-8445-2b0bc04642cb/call-myTask/execution/rc.tmp /cromwell-executions/myWorkflow/3d472760-433f-4177-8445-2b0bc04642cb/call-myTask/execution/rc
