#!/bin/bash

cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/d6338c92-2c22-476e-82fd-29afc67a3dc6/call-myTask/execution
tmpDir=$(mkdir -p "/Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/d6338c92-2c22-476e-82fd-29afc67a3dc6/call-myTask/tmp.7bfe5bf8" && echo "/Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/d6338c92-2c22-476e-82fd-29afc67a3dc6/call-myTask/tmp.7bfe5bf8")

export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/d6338c92-2c22-476e-82fd-29afc67a3dc6/call-myTask/execution

)
outd6338c92="${tmpDir}/out.$$" errd6338c92="${tmpDir}/err.$$"
mkfifo "$outd6338c92" "$errd6338c92"
trap 'rm "$outd6338c92" "$errd6338c92"' EXIT
tee '/Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/d6338c92-2c22-476e-82fd-29afc67a3dc6/call-myTask/execution/stdout' < "$outd6338c92" &
tee '/Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/d6338c92-2c22-476e-82fd-29afc67a3dc6/call-myTask/execution/stderr' < "$errd6338c92" >&2 &
(
cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/d6338c92-2c22-476e-82fd-29afc67a3dc6/call-myTask/execution


set -exo pipefail
mkdir bundle
echo /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/d6338c92-2c22-476e-82fd-29afc67a3dc6/call-myTask/inputs/-223602523/bundle.tar.gz
tar -xzf /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/d6338c92-2c22-476e-82fd-29afc67a3dc6/call-myTask/inputs/-223602523/bundle.tar.gz -C bundle
echo realpath bundle 
mv bundle/*/* bundle
PWD=/Users/mkumar1/wdl/tar_example
python3 /Users/mkumar1/wdl/tar_example/script.py -t $PWD/bundle/exomiser_genome_template_b38.yml -o bundle.tar.gz.out_file
)  > "$outd6338c92" 2> "$errd6338c92"
echo $? > /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/d6338c92-2c22-476e-82fd-29afc67a3dc6/call-myTask/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/d6338c92-2c22-476e-82fd-29afc67a3dc6/call-myTask/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/d6338c92-2c22-476e-82fd-29afc67a3dc6/call-myTask/execution
sync


)
mv /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/d6338c92-2c22-476e-82fd-29afc67a3dc6/call-myTask/execution/rc.tmp /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/d6338c92-2c22-476e-82fd-29afc67a3dc6/call-myTask/execution/rc
