#!/bin/bash

cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/0071f5e0-0c3e-421e-b5db-ccff02595efc/call-myTask/execution
tmpDir=$(mkdir -p "/Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/0071f5e0-0c3e-421e-b5db-ccff02595efc/call-myTask/tmp.1b00d2d5" && echo "/Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/0071f5e0-0c3e-421e-b5db-ccff02595efc/call-myTask/tmp.1b00d2d5")

export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/0071f5e0-0c3e-421e-b5db-ccff02595efc/call-myTask/execution

)
out0071f5e0="${tmpDir}/out.$$" err0071f5e0="${tmpDir}/err.$$"
mkfifo "$out0071f5e0" "$err0071f5e0"
trap 'rm "$out0071f5e0" "$err0071f5e0"' EXIT
tee '/Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/0071f5e0-0c3e-421e-b5db-ccff02595efc/call-myTask/execution/stdout' < "$out0071f5e0" &
tee '/Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/0071f5e0-0c3e-421e-b5db-ccff02595efc/call-myTask/execution/stderr' < "$err0071f5e0" >&2 &
(
cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/0071f5e0-0c3e-421e-b5db-ccff02595efc/call-myTask/execution


set -exo pipefail
mkdir bundle
echo /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/0071f5e0-0c3e-421e-b5db-ccff02595efc/call-myTask/inputs/-223602523/bundle.tar.gz
tar -xzf /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/0071f5e0-0c3e-421e-b5db-ccff02595efc/call-myTask/inputs/-223602523/bundle.tar.gz -C bundle
path=$(realpath bundle)
echo $path 
mv bundle/*/* bundle
python3 /Users/mkumar1/wdl/tar_example/script.py -t $path/exomiser_genome_template_b38.yml -o bundle.tar.gz.out_file
)  > "$out0071f5e0" 2> "$err0071f5e0"
echo $? > /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/0071f5e0-0c3e-421e-b5db-ccff02595efc/call-myTask/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/0071f5e0-0c3e-421e-b5db-ccff02595efc/call-myTask/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/0071f5e0-0c3e-421e-b5db-ccff02595efc/call-myTask/execution
sync


)
mv /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/0071f5e0-0c3e-421e-b5db-ccff02595efc/call-myTask/execution/rc.tmp /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/0071f5e0-0c3e-421e-b5db-ccff02595efc/call-myTask/execution/rc
