#!/bin/bash

cd /cromwell-executions/myWorkflow/462afa44-60f0-4eb6-bd74-f05d5a510064/call-myTask/execution
tmpDir=$(mkdir -p "/cromwell-executions/myWorkflow/462afa44-60f0-4eb6-bd74-f05d5a510064/call-myTask/tmp.9d5527ec" && echo "/cromwell-executions/myWorkflow/462afa44-60f0-4eb6-bd74-f05d5a510064/call-myTask/tmp.9d5527ec")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/myWorkflow/462afa44-60f0-4eb6-bd74-f05d5a510064/call-myTask/execution

)
out462afa44="${tmpDir}/out.$$" err462afa44="${tmpDir}/err.$$"
mkfifo "$out462afa44" "$err462afa44"
trap 'rm "$out462afa44" "$err462afa44"' EXIT
tee '/cromwell-executions/myWorkflow/462afa44-60f0-4eb6-bd74-f05d5a510064/call-myTask/execution/stdout' < "$out462afa44" &
tee '/cromwell-executions/myWorkflow/462afa44-60f0-4eb6-bd74-f05d5a510064/call-myTask/execution/stderr' < "$err462afa44" >&2 &
(
cd /cromwell-executions/myWorkflow/462afa44-60f0-4eb6-bd74-f05d5a510064/call-myTask/execution


set -exo pipefail
mkdir bundle
echo /cromwell-executions/myWorkflow/462afa44-60f0-4eb6-bd74-f05d5a510064/call-myTask/inputs/-223602523/bundle.tar.gz
tar -xzf /cromwell-executions/myWorkflow/462afa44-60f0-4eb6-bd74-f05d5a510064/call-myTask/inputs/-223602523/bundle.tar.gz -C bundle
path=$(realpath bundle)
echo $path 
mv bundle/*/* bundle

python3 /script.py -t $path/exomiser_genome_template_b38.yml -o bundle.tar.gz.out_file
)  > "$out462afa44" 2> "$err462afa44"
echo $? > /cromwell-executions/myWorkflow/462afa44-60f0-4eb6-bd74-f05d5a510064/call-myTask/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/myWorkflow/462afa44-60f0-4eb6-bd74-f05d5a510064/call-myTask/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/myWorkflow/462afa44-60f0-4eb6-bd74-f05d5a510064/call-myTask/execution
sync


)
mv /cromwell-executions/myWorkflow/462afa44-60f0-4eb6-bd74-f05d5a510064/call-myTask/execution/rc.tmp /cromwell-executions/myWorkflow/462afa44-60f0-4eb6-bd74-f05d5a510064/call-myTask/execution/rc
