#!/bin/bash

cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/06dd9c29-71a5-40dc-a8d4-53f14c0ac5db/call-myTask/execution
tmpDir=$(mkdir -p "/Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/06dd9c29-71a5-40dc-a8d4-53f14c0ac5db/call-myTask/tmp.14a98b34" && echo "/Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/06dd9c29-71a5-40dc-a8d4-53f14c0ac5db/call-myTask/tmp.14a98b34")

export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/06dd9c29-71a5-40dc-a8d4-53f14c0ac5db/call-myTask/execution

)
out06dd9c29="${tmpDir}/out.$$" err06dd9c29="${tmpDir}/err.$$"
mkfifo "$out06dd9c29" "$err06dd9c29"
trap 'rm "$out06dd9c29" "$err06dd9c29"' EXIT
tee '/Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/06dd9c29-71a5-40dc-a8d4-53f14c0ac5db/call-myTask/execution/stdout' < "$out06dd9c29" &
tee '/Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/06dd9c29-71a5-40dc-a8d4-53f14c0ac5db/call-myTask/execution/stderr' < "$err06dd9c29" >&2 &
(
cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/06dd9c29-71a5-40dc-a8d4-53f14c0ac5db/call-myTask/execution


set -exo pipefail
mkdir bundle
echo /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/06dd9c29-71a5-40dc-a8d4-53f14c0ac5db/call-myTask/inputs/-223602523/bundle.tar.gz
tar -xzf /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/06dd9c29-71a5-40dc-a8d4-53f14c0ac5db/call-myTask/inputs/-223602523/bundle.tar.gz -C bundle
path=$(realpath bundle)
echo $path 
mv bundle/*/* bundle

python3 /Users/mkumar1/wdl/tar_example/script.py -t $path/exomiser_genome_template_b38.yml -o bundle.tar.gz.out_file
)  > "$out06dd9c29" 2> "$err06dd9c29"
echo $? > /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/06dd9c29-71a5-40dc-a8d4-53f14c0ac5db/call-myTask/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/06dd9c29-71a5-40dc-a8d4-53f14c0ac5db/call-myTask/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/06dd9c29-71a5-40dc-a8d4-53f14c0ac5db/call-myTask/execution
sync


)
mv /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/06dd9c29-71a5-40dc-a8d4-53f14c0ac5db/call-myTask/execution/rc.tmp /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/06dd9c29-71a5-40dc-a8d4-53f14c0ac5db/call-myTask/execution/rc
