#!/bin/bash

cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/746fa1a9-cb24-4ae4-b105-4a6f3b120bc9/call-myTask/execution
tmpDir=$(mkdir -p "/Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/746fa1a9-cb24-4ae4-b105-4a6f3b120bc9/call-myTask/tmp.0a303ecc" && echo "/Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/746fa1a9-cb24-4ae4-b105-4a6f3b120bc9/call-myTask/tmp.0a303ecc")

export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/746fa1a9-cb24-4ae4-b105-4a6f3b120bc9/call-myTask/execution

)
out746fa1a9="${tmpDir}/out.$$" err746fa1a9="${tmpDir}/err.$$"
mkfifo "$out746fa1a9" "$err746fa1a9"
trap 'rm "$out746fa1a9" "$err746fa1a9"' EXIT
tee '/Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/746fa1a9-cb24-4ae4-b105-4a6f3b120bc9/call-myTask/execution/stdout' < "$out746fa1a9" &
tee '/Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/746fa1a9-cb24-4ae4-b105-4a6f3b120bc9/call-myTask/execution/stderr' < "$err746fa1a9" >&2 &
(
cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/746fa1a9-cb24-4ae4-b105-4a6f3b120bc9/call-myTask/execution


set -exo pipefail
mkdir bundle
tar -xzf /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/746fa1a9-cb24-4ae4-b105-4a6f3b120bc9/call-myTask/inputs/-223602523/bundle.tar.gz -C bundle
mv bundle/*/* bundle
PWD=/Users/mkumar1/Desktop/apps/Exomiser
python3 /Users/mkumar1/wdl/cromwell/script.py -t $PWD/bundle/exomiser_genome_template_b38.yml -o bundle.tar.gz.out_file
)  > "$out746fa1a9" 2> "$err746fa1a9"
echo $? > /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/746fa1a9-cb24-4ae4-b105-4a6f3b120bc9/call-myTask/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/746fa1a9-cb24-4ae4-b105-4a6f3b120bc9/call-myTask/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/746fa1a9-cb24-4ae4-b105-4a6f3b120bc9/call-myTask/execution
sync


)
mv /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/746fa1a9-cb24-4ae4-b105-4a6f3b120bc9/call-myTask/execution/rc.tmp /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/746fa1a9-cb24-4ae4-b105-4a6f3b120bc9/call-myTask/execution/rc
