#!/bin/bash

cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/458eaf43-5178-46bc-9221-523ada30c150/call-myTask/execution
tmpDir=$(mkdir -p "/Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/458eaf43-5178-46bc-9221-523ada30c150/call-myTask/tmp.38e9c68c" && echo "/Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/458eaf43-5178-46bc-9221-523ada30c150/call-myTask/tmp.38e9c68c")

export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/458eaf43-5178-46bc-9221-523ada30c150/call-myTask/execution

)
out458eaf43="${tmpDir}/out.$$" err458eaf43="${tmpDir}/err.$$"
mkfifo "$out458eaf43" "$err458eaf43"
trap 'rm "$out458eaf43" "$err458eaf43"' EXIT
tee '/Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/458eaf43-5178-46bc-9221-523ada30c150/call-myTask/execution/stdout' < "$out458eaf43" &
tee '/Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/458eaf43-5178-46bc-9221-523ada30c150/call-myTask/execution/stderr' < "$err458eaf43" >&2 &
(
cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/458eaf43-5178-46bc-9221-523ada30c150/call-myTask/execution


set -exo pipefail
mkdir bundle
tar -xzf /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/458eaf43-5178-46bc-9221-523ada30c150/call-myTask/inputs/-223602523/bundle.tar.gz -C bundle
mv bundle/*/* bundle
PWD=/Users/mkumar1/Desktop/apps/Exomiser
python3 /Users/mkumar1/wdl/cromwell/script.py -t /Users/mkumar1/wdl/tar_example/bundle/exomiser_genome_template_b38.yml -o bundle.tar.gz.out_file
)  > "$out458eaf43" 2> "$err458eaf43"
echo $? > /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/458eaf43-5178-46bc-9221-523ada30c150/call-myTask/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/458eaf43-5178-46bc-9221-523ada30c150/call-myTask/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/458eaf43-5178-46bc-9221-523ada30c150/call-myTask/execution
sync


)
mv /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/458eaf43-5178-46bc-9221-523ada30c150/call-myTask/execution/rc.tmp /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/458eaf43-5178-46bc-9221-523ada30c150/call-myTask/execution/rc
