#!/bin/bash

cd /cromwell-executions/myWorkflow/7297b3dd-67cd-4ded-9afb-bf1cd17302ba/call-myTask/execution
tmpDir=$(mkdir -p "/cromwell-executions/myWorkflow/7297b3dd-67cd-4ded-9afb-bf1cd17302ba/call-myTask/tmp.647a6375" && echo "/cromwell-executions/myWorkflow/7297b3dd-67cd-4ded-9afb-bf1cd17302ba/call-myTask/tmp.647a6375")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/myWorkflow/7297b3dd-67cd-4ded-9afb-bf1cd17302ba/call-myTask/execution

)
out7297b3dd="${tmpDir}/out.$$" err7297b3dd="${tmpDir}/err.$$"
mkfifo "$out7297b3dd" "$err7297b3dd"
trap 'rm "$out7297b3dd" "$err7297b3dd"' EXIT
tee '/cromwell-executions/myWorkflow/7297b3dd-67cd-4ded-9afb-bf1cd17302ba/call-myTask/execution/stdout' < "$out7297b3dd" &
tee '/cromwell-executions/myWorkflow/7297b3dd-67cd-4ded-9afb-bf1cd17302ba/call-myTask/execution/stderr' < "$err7297b3dd" >&2 &
(
cd /cromwell-executions/myWorkflow/7297b3dd-67cd-4ded-9afb-bf1cd17302ba/call-myTask/execution


set -exo pipefail
mkdir bundle
echo /cromwell-executions/myWorkflow/7297b3dd-67cd-4ded-9afb-bf1cd17302ba/call-myTask/inputs/-223602523/bundle.tar.gz
tar -xzf /cromwell-executions/myWorkflow/7297b3dd-67cd-4ded-9afb-bf1cd17302ba/call-myTask/inputs/-223602523/bundle.tar.gz -C bundle
path=$(realpath bundle)
echo $path 
mv bundle/*/* bundle

python3 script.py -t $path/exomiser_genome_template_b38.yml -o bundle.tar.gz.out_file
)  > "$out7297b3dd" 2> "$err7297b3dd"
echo $? > /cromwell-executions/myWorkflow/7297b3dd-67cd-4ded-9afb-bf1cd17302ba/call-myTask/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/myWorkflow/7297b3dd-67cd-4ded-9afb-bf1cd17302ba/call-myTask/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/myWorkflow/7297b3dd-67cd-4ded-9afb-bf1cd17302ba/call-myTask/execution
sync


)
mv /cromwell-executions/myWorkflow/7297b3dd-67cd-4ded-9afb-bf1cd17302ba/call-myTask/execution/rc.tmp /cromwell-executions/myWorkflow/7297b3dd-67cd-4ded-9afb-bf1cd17302ba/call-myTask/execution/rc
