#!/bin/bash

cd /cromwell-executions/myWorkflow/6550032d-d8a9-4b06-b334-5e9cd0321a48/call-myTask/execution
tmpDir=$(mkdir -p "/cromwell-executions/myWorkflow/6550032d-d8a9-4b06-b334-5e9cd0321a48/call-myTask/tmp.5195311c" && echo "/cromwell-executions/myWorkflow/6550032d-d8a9-4b06-b334-5e9cd0321a48/call-myTask/tmp.5195311c")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/myWorkflow/6550032d-d8a9-4b06-b334-5e9cd0321a48/call-myTask/execution

)
out6550032d="${tmpDir}/out.$$" err6550032d="${tmpDir}/err.$$"
mkfifo "$out6550032d" "$err6550032d"
trap 'rm "$out6550032d" "$err6550032d"' EXIT
tee '/cromwell-executions/myWorkflow/6550032d-d8a9-4b06-b334-5e9cd0321a48/call-myTask/execution/stdout' < "$out6550032d" &
tee '/cromwell-executions/myWorkflow/6550032d-d8a9-4b06-b334-5e9cd0321a48/call-myTask/execution/stderr' < "$err6550032d" >&2 &
(
cd /cromwell-executions/myWorkflow/6550032d-d8a9-4b06-b334-5e9cd0321a48/call-myTask/execution


set -exo pipefail
mkdir bundle
echo /cromwell-executions/myWorkflow/6550032d-d8a9-4b06-b334-5e9cd0321a48/call-myTask/inputs/-223602523/bundle.tar.gz
tar -xzf /cromwell-executions/myWorkflow/6550032d-d8a9-4b06-b334-5e9cd0321a48/call-myTask/inputs/-223602523/bundle.tar.gz -C bundle
path=$(realpath bundle)
echo $path 
mv bundle/*/* bundle

python3 /usr/src/app/script.py -t $path/exomiser_genome_template_b38.yml -o bundle.tar.gz.out_file
)  > "$out6550032d" 2> "$err6550032d"
echo $? > /cromwell-executions/myWorkflow/6550032d-d8a9-4b06-b334-5e9cd0321a48/call-myTask/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/myWorkflow/6550032d-d8a9-4b06-b334-5e9cd0321a48/call-myTask/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/myWorkflow/6550032d-d8a9-4b06-b334-5e9cd0321a48/call-myTask/execution
sync


)
mv /cromwell-executions/myWorkflow/6550032d-d8a9-4b06-b334-5e9cd0321a48/call-myTask/execution/rc.tmp /cromwell-executions/myWorkflow/6550032d-d8a9-4b06-b334-5e9cd0321a48/call-myTask/execution/rc
