#!/bin/bash

cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/657be04c-6a2c-4bab-9d50-8deea373f1ce/call-myTask/execution
tmpDir=$(mkdir -p "/Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/657be04c-6a2c-4bab-9d50-8deea373f1ce/call-myTask/tmp.389ad3a4" && echo "/Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/657be04c-6a2c-4bab-9d50-8deea373f1ce/call-myTask/tmp.389ad3a4")

export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/657be04c-6a2c-4bab-9d50-8deea373f1ce/call-myTask/execution

)
out657be04c="${tmpDir}/out.$$" err657be04c="${tmpDir}/err.$$"
mkfifo "$out657be04c" "$err657be04c"
trap 'rm "$out657be04c" "$err657be04c"' EXIT
tee '/Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/657be04c-6a2c-4bab-9d50-8deea373f1ce/call-myTask/execution/stdout' < "$out657be04c" &
tee '/Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/657be04c-6a2c-4bab-9d50-8deea373f1ce/call-myTask/execution/stderr' < "$err657be04c" >&2 &
(
cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/657be04c-6a2c-4bab-9d50-8deea373f1ce/call-myTask/execution


set -exo pipefail
mkdir bundle
echo /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/657be04c-6a2c-4bab-9d50-8deea373f1ce/call-myTask/inputs/-223602523/bundle.tar.gz
tar -xzf /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/657be04c-6a2c-4bab-9d50-8deea373f1ce/call-myTask/inputs/-223602523/bundle.tar.gz -C bundle
mv bundle/*/* bundle
PWD=/Users/mkumar1/wdl/tar_example
python3 /Users/mkumar1/wdl/tar_example/script.py -t $PWD/bundle/exomiser_genome_template_b38.yml -o bundle.tar.gz.out_file
)  > "$out657be04c" 2> "$err657be04c"
echo $? > /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/657be04c-6a2c-4bab-9d50-8deea373f1ce/call-myTask/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/657be04c-6a2c-4bab-9d50-8deea373f1ce/call-myTask/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/657be04c-6a2c-4bab-9d50-8deea373f1ce/call-myTask/execution
sync


)
mv /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/657be04c-6a2c-4bab-9d50-8deea373f1ce/call-myTask/execution/rc.tmp /Users/mkumar1/wdl/tar_example/cromwell-executions/myWorkflow/657be04c-6a2c-4bab-9d50-8deea373f1ce/call-myTask/execution/rc
